### ISSUE TITLE
Passing a string function to addRule raises an exception

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#10]
`.addRule("required", null, () => 'Anonymous??? ')`
generates the following error in the console:
```
(20,19): error TS2346: Supplied parameters do not match any signature of call target.
```
The function still generates the message correctly, so I'm not sure where the error is generated.

**Comment by grofit** [comment]
Will check and verify at some point over the weekend.

**Comment by jsobell** [comment]
Ah, it's a webpack generated error.
I think this might be the issue:
https://github.com/grofit/treacherous/blob/afc7f64b275dd13aaf861158f6aab98af4d69d10/src/rulesets/ruleset-builder.ts#L29
I suspect the call to the override may have to be in a closure.

**Comment by jsobell** [comment]
Caused by order of operator syntax in TypeScript function definition.
Resolved in PR https://github.com/grofit/treacherous/pull/12
