### ISSUE TITLE
Thoughts re handling of error tests

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#14]
Some thoughts...
How to handle the fact that some fields should only be validated on blur, change, or whenever.

`valtype` (bitmapped field?): 0=full check, 1=propertycheck, 2=propertychanged
is passed in to any rule check based on the original reason for the validation process. It returns true if the validation is to be processed.

Default for any rule is:
`applies = (valtype) => { return true; }`

If the user calls validate, all returning true for `applies(0)` are checked
If the user calls validateProperty('X'), all returning true for `applies(1)` are checked
If the user (via a plugin, e.g. UI binding to model) modifies property 'X' in the model, all returning true for `applies(2)` are checked

But... left like this, if the user modifies property 'X' in the model through code, all with 2 are checked, so we will get the errors generated on the UI even if we're loading a record's JSON from the server. 
One simple solution may be to have the concept of suspending validation (and resetting dirty checking when it is resumed).
Given that (in theory) the user should always be calling validate() anyway (which can't be suspended?), it's safe to accept that so long as the user always uses validate() before consuming the data, there won't be any issues.

A) Rule defined to apply always to any validation attempt:
`applies = (valtype) => { return true; };`

B) Rule defined to only apply on a full validation:
`applies = (valtype) => { return (!valtype); };`

C) Rule defined to only apply on a full validation or when the user requests validation of this field by name: (is this likely to be a scenario?)
`applies = (valtype) => { return !valtype || (valtype & 1); };`

D) Rule defined to only apply on a full validation or when the property has changed through code or binding to the UI:
`applies = (valtype) => { return !valtype || (valtype & 2); };`

In addition, because `applies` is a function, the dev can create a rule to only perform validation under chosen situations

To assign onBlur, bindings will update the model property, so the rule will only apply when the user changes data.
If the validation is to apply on onBlur even if data is unchanged, the handler for the input field must call `validateProperty('X')` to force evaluation of that RuleLink without going through the property watcher.  By default this will only fire the validation if the link is set to A or C.

**Comment by jsobell** [comment]
Actually, this is a variation of the .withGuard() feature I was looking at adding to the rules.
If the user only wants to validate the email address if `hasEmail` is true, the rule can say
```
.withGuard( (m,v) => { return m.hasEmail; })
```
The above code is virtually identical, with the reason being also passed in as a parameter.
The only addition is the flow of the reason down to the call to the RuleLink check.

**Comment by jsobell** [comment]
or perhaps 
```
.appliesIf( (m,v) => { return m.hasEmail; })
```
?

**Comment by grofit** [comment]
after our discussion in gitter I am ok with the `appliesIf` approach, however as mentioned my only worry is that if you are defining the models/rules in a module and consuming it in multiple other modules (i.e an API that shares models as the contracts between front and back end or something) you need to know the predicate at the point of rule assignment, and you may not have the *same* data available on each module consuming it, so that is a potential worry however the general approach you have put forward seems to solve most common scenarios.

**Comment by grofit** [comment]
The `appliesIf` feature has been added in the latest PR merge, feel free to re-open if more discussion is needed but I see future features and changes to applies if being done in new issues/feature tickets.
