### ISSUE TITLE
Wallaby timeouts... All promise returning calls require catch(done)

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#15]
The reason errors in Wallaby fail with 2000ms timeouts is because there are no catches on the promises in the tests.
Add `.catch(done)` to the end of each `then()` in the tests causes any error to correctly logged.
e.g.
```
        validationGroup.isValid()
            .then(function(isValid){
                expect(isValid).to.be.true;
                validationGroup.release();
                done();
            }).catch(done);
```

**Comment by grofit** [comment]
I believe this is all fixed with the latest PR so will flag it as complete feel free to re-open.
