### ISSUE TITLE
Validation on group construction

### ISSUE THREAD

**Issue by MaximBalaganskiy** [grofit/treacherous#19]
Validation happens immediately in validation group constructor. Having UI validation in mind, it would be better to not validate straightaway so that just loaded empty form does not have error messages

**Comment by grofit** [comment]
Problem is UI is the exception here not the rule, generally you want all validation to occur as soon as possible, now I agree you may not want that to be displayed in the UI however I currently see that as a UI problem not a treacherous problem.

There are currently some discussions happening around being able to restrict validation based upon predicates `appliesIf` which is currently available in `0.10.0` however we still need to talk around the "reason" aspect so you could specify that something should only be validated if it is an explicit call not automatic change.

Once those discussions are had you should be able to do some of this at the treacherous level.

**Comment by MaximBalaganskiy** [comment]
Although the new method might work it will be hugely inconvenient if you
have lots of rules. an option you could just have a parameter in the
constructor saying whether or not to validate during the construction time

**Comment by grofit** [comment]
It is a possibility to provide a parameter to tell it not to validate when it constructs the model, as that is of little impact and it can be opt-in rather than opt-out.

Will have a bit more of a think on it and get back to you.

**Comment by grofit** [comment]
Just a note on this in 0.11.0 startup validation has been disabled so you need to explicitly call `validate` or change a property for validation to fire, not sure if this provides the functionality you were requesting.

**Comment by MaximBalaganskiy** [comment]
This should do it
