### ISSUE TITLE
Double nesting addRulesetForEach

### ISSUE THREAD

**Issue by Interopnl** [grofit/treacherous#21]
Is it possible to (double) rules-sets?

The order rules-set works properly, but i can't seem get the (nested) product rule-set to work.

```javascript
 // product validation rules
 this.productRuleSet = createRuleset()
                               .forProperty("deliveryDate")
                                   .addRule("required")
                               .build();

 // order validation rules
 this.orderRuleSet = createRuleset()
                               .forProperty("products")
                                   .addRulesetForEach(this.productRuleSet)
                               .build();

 // invoice validation rules
 this.invoiceRuleSet = createRuleset()
                                  .forProperty("orders")
                                    .addRulesetForEach(this.orderRuleSet)
                                  .build();      

 this.invoiceValGroup = createGroup(this.invoice, this.invoiceRuleSet);
```

**Comment by grofit** [comment]
hello, off top of my head you should be able to do what you have above as it just checks at each level in the model is it a `RuleLink` a `RuleSet` or a `ForEachRule` there is some more complexity to it but that should be able it, so if it doesnt work I will make an explicit test for it and verify later.

Currently there is a merge about to take place from one of the forks so this may end up being done after that.

**Comment by grofit** [comment]
Just done a quick test to check this behaviour:

```js
    it("should correctly validate foreach in foreach", function(done){
        // product validation rules
        var productRuleSet = createRuleset()
            .forProperty("deliveryDate")
            .addRule("required")
            .build();

        // order validation rules
        var orderRuleSet = createRuleset()
            .forProperty("products")
            .addRulesetForEach(productRuleSet)
            .build();

        // invoice validation rules
        var invoiceRuleSet = createRuleset()
            .forProperty("orders")
            .addRulesetForEach(orderRuleSet)
            .build();

        var dummyProduct1 = { deliveryDate: null };
        var dummyProduct2 = { deliveryDate: null };
        var dummyProduct3 = { deliveryDate: null };
        var dummyProduct4 = { deliveryDate: null };

        var dummyOrder1 = { products: [ dummyProduct1, dummyProduct2 ] };
        var dummyOrder2 = { products: [ dummyProduct3, dummyProduct4 ] };

        var dummyInvoice = {
            orders: [ dummyOrder1, dummyOrder2 ]
        };

        var invoiceValidationGroup = createGroup(dummyInvoice, invoiceRuleSet);

        invoiceValidationGroup.getModelErrors()
            .then(function(errors){
                console.log("errors", errors);
                done("error");
            }).catch(done);
    });
```

and it outputs:

```
'errors', Object {
 orders[0].products[0].deliveryDate: 'This field is required', 
 orders[0].products[1].deliveryDate: 'This field is required', 
 orders[1].products[0].deliveryDate: 'This field is required', 
 orders[1].products[1].deliveryDate: 'This field is required'
}
```

So it looks like it works as expected, do you not get the above behaviour? if not can you make a quick repro on something like cloud9 etc?

**Comment by Interopnl** [comment]
The problem was that the array was not initialized before creating the validation-group.

    it("should correctly validate foreach in foreach", function(done){
        // product validation rules
        var productRuleSet = createRuleset()
            .forProperty("deliveryDate")
            .addRule("required")
            .build();

        // order validation rules
        var orderRuleSet = createRuleset()
            .forProperty("products")
            .addRulesetForEach(productRuleSet)
            .build();

        // invoice validation rules
        var invoiceRuleSet = createRuleset()
            .forProperty("orders")
            .addRulesetForEach(orderRuleSet)
            .build();

        var dummyProduct1 = { deliveryDate: null };
        var dummyProduct2 = { deliveryDate: null };
        var dummyProduct3 = { deliveryDate: null };
        var dummyProduct4 = { deliveryDate: null };

        var dummyOrder1 = { products: [ ] };
        var dummyOrder2 = { products: [ dummyProduct3, dummyProduct4 ] };

        var dummyInvoice = {
            orders: [ dummyOrder1, dummyOrder2 ]
        };

        var invoiceValidationGroup = createGroup(dummyInvoice, invoiceRuleSet);


        invoiceValidationGroup.getModelErrors()
            .then(function(errors){
                console.log("errors", errors);
                done("error");
            }).catch(done);
    });

**Comment by Interopnl** [comment]
the problem was that the array was not initialized before creating the validation group.

something like te following test

```javascript
it("should correctly validate dynamic nested arrays", function(done){
    // product validation rules
    var productRuleSet = createRuleset()
        .forProperty("deliveryDate")
        .addRule("required")
        .build();

    // order validation rules
    var orderRuleSet = createRuleset()
        .forProperty("products")
        .addRulesetForEach(productRuleSet)
        .build();

    // invoice validation rules
    var invoiceRuleSet = createRuleset()
        .forProperty("orders")
        .addRulesetForEach(orderRuleSet)
        .build();

    var dummyProduct1 = { deliveryDate: null };
    var dummyProduct2 = { deliveryDate: null };
    var dummyProduct3 = { deliveryDate: null };
    var dummyProduct4 = { deliveryDate: null };

    var dummyOrder1 = { products: [ ] };
    var dummyOrder2 = { products: [ dummyProduct3, dummyProduct4 ] };

    var dummyInvoice = {
        orders: [ dummyOrder1, dummyOrder2 ]
    };

    var invoiceValidationGroup = createGroup(dummyInvoice, invoiceRuleSet);

   dummyOrder1.products.push(dummyProduct1);
   dummyOrder1.products.push(dummyProduct2);

    invoiceValidationGroup.getModelErrors()
        .then(function(errors){
            console.log("errors", errors);
            done("error");
        }).catch(done);
});`

**Comment by grofit** [comment]
will try it out for you shortly

**Comment by grofit** [comment]
ok so doing the test you have there outputs:

```
'errors', Object {
orders[1].products[0].deliveryDate: 'This field is required', 
orders[1].products[1].deliveryDate: 'This field is required'
}
```

So it seems that for some reason it is not picking up the changes, will look into it.

**Comment by Interopnl** [comment]
Okay, thanks for testing this out. Let me know if you need my help.

**Comment by grofit** [comment]
RIGHT!

The crux of it is that the change is not picked up in time, as the default re-check of a model happens every 500ms (configurable), so if a change happens it does not notify the model about it until the next dirty check happens.

So in this case what is happening is that you are changing it, then reporting on it and the change has not flagged up yet, so it would report only the "known" errors. Now this has been an on-going trouble as there are a couple of *fixes*, one is to do something like delaying calls until after the next model check has happened, another would be to manually trigger the model watcher before you run to confirm any changes are bubbled. So some discussion needs to happen around that.

**Comment by Interopnl** [comment]
Thanks for the help, i will try solve this issue with suggested work-arounds.

**Comment by grofit** [comment]
sorry my above stuff is not a *solution* for you, its just a way for me to prove what the problem is. We will implement a solution in the core lib its just until this merge is done I dont want to rock the boat any further, so the next version should hopefully have a fix for this, until then you *can* do a delay temporarily but its just going to be a hack.

**Comment by grofit** [comment]
right in the next version there is a temporary fix in for this, where if you call `getModelErrors` it automatically re-validates the entire stack, this is a simple way to solve this issue while the whole discussion on how to best handle non reactive validators and other bits kicks off. The version you will want is 0.11.0 so keep an eye out, I should hopefully release it at some point over the weekend or worst case early next week.

**Comment by Interopnl** [comment]
Thanks for the temporary fix, will try it out once it's released.

**Comment by jsobell** [comment]
OK, so to clarify, the issue here (which is solved in the latest release) is that `getModelErrors()` isn't intended to perform the validation, but to intelligently wait for any pending rules to complete then return a list of errors.
If you want to know if there are any errors then you must use the `validate()` method, as that returns whether or not the model has any errors, without waiting for the timer on the model change detector to fire. When you then call `getModelErrors()` it will instantly return the list of errors.
So here's the above test case changing the model and showing the reflected errors immediately:

```
    it("should correctly validate dynamic nested arrays", function(done) {

        // product validation rules
        var productRuleSet = createRuleset()
            .forProperty("deliveryDate")
            .addRule("required")
            .build();

        // order validation rules
        var orderRuleSet = createRuleset()
            .forProperty("products")
            .addRulesetForEach(productRuleSet)
            .build();

        // invoice validation rules
        var invoiceRuleSet = createRuleset()
            .forProperty("orders")
            .addRulesetForEach(orderRuleSet)
            .build();

        var dummyProduct1 = {deliveryDate: null};
        var dummyProduct2 = {deliveryDate: null};
        var dummyProduct3 = {deliveryDate: null};
        var dummyProduct4 = {deliveryDate: null};

        var dummyOrder1 = {products: []};
        var dummyOrder2 = {products: [dummyProduct3, dummyProduct4]};

        var dummyInvoice = {
            orders: [dummyOrder1, dummyOrder2]
        };

        var invoiceValidationGroup = createGroup(dummyInvoice, invoiceRuleSet);

        var errorCount = () => Object.keys(invoiceValidationGroup.propertyErrors).length;

        dummyOrder1.products.push(dummyProduct1);
        dummyOrder1.products.push(dummyProduct2);

        invoiceValidationGroup.validate().then(isvalid => invoiceValidationGroup.getModelErrors()
            .then(function (errors) {
                expect(isvalid).to.be.false;
                expect(errorCount()).to.equal(4);

                dummyInvoice.orders[0].products[1].deliveryDate = new Date();

                invoiceValidationGroup.validate()
                    .then(function (isvalid) {
                        expect(isvalid).to.be.false;
                        expect(errorCount()).to.equal(3);

                        dummyInvoice.orders[0].products[1].deliveryDate = null;

                        invoiceValidationGroup.validate()
                            .then(isvalid => {
                                expect(isvalid).to.be.false;
                                expect(errorCount()).to.equal(4);
                                done();

                            }).catch(done);
                    }).catch(done);
            }).catch(done)
        ).catch(done);
    });
```
