### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by TimBailey-pnk** [grofit/treacherous#26]
I require multilingual support for my application.
I'm using Aurelia, I prefer your validation library to the official one, the API is very similar but i prefer your approach for unit testing.

I like the .withMessageKey() configuration method in the Aurelia-Validation library, did you have any thoughts on how it should work inside Treacherous?

I can submit a PR.

**Comment by jsobell** [comment]
The message string can be a function of you like, so you could create a T() function that takes a message key and looks at the context language, and pass a call to T('MSG005') or whatever as the message in your rules.

**Comment by TimBailey-pnk** [comment]
Thanks for the response, where would that fit in here....
```
    let ruleset = createRuleset()
      .forProperty('name')
        .addRule('required')
      .forProperty('email')
        .addRule('required')
        .addRule('email')
      .forProperty('password')
        .addRule('required')
      .forProperty('passwordConfirm')
        .addRule('required')
        .addRule('matches', 'password')
      .build()
```
Currently the rules are hard coded to English strings, ie "This field is mypassword but should match password" (which seems to also suggest I need a matchPassword rule that doesnt display the password in the error message)

**Comment by TimBailey-pnk** [comment]
Ah, right, yes found `.withMessage()` now investigating, thanks

**Comment by grofit** [comment]
Hello,

Sorry quite hectic time for me at the moment, as mentioned *currently* you can use `.withMessage()` but going forward the idea was to have a message registry which would link a rule [`required`] and a language [`en-gb`] to a message.

This has not been implemented yet, and it is unsure how internationalisation would work with this, but there is some rough idea for this to be implemented going forward.

**Comment by TimBailey-pnk** [comment]
Hi, yes, using .withMessage with a custom validation strategy that looks up the messageid from aurelia-i18n  library.  Perhaps would be better to generalise that process via a plugable interface.  This way you could have a registry implementation or a aurelia-i18n implementaion.

**Comment by grofit** [comment]
I have had some spare time recently and have got an approach locally for handling localization of messages. The problem really is trying to make sure it is extensible so one of the many i18n style frameworks can be hooked in, or if people dont care about that can just use local files or even not have to do anything and just stick with `en-us` as the default.

Anyway I am hoping to get this pushed up next week and cause some breaking changes, mainly on validation rules, but the interface it will be following will be something like:

```ts
export interface ILocaleHandler
{
    getLocale(): string;
    useLocale(localeCode: string, localeDataorOptions?: any): Promise<void>;
    getMessage(ruleName: string, ruleOptions: any, modelResolver: IModelResolver, propertyName: string) : Promise<string>;
}
```

This approach *should* allow for people to use async i18n back end calls if they want to do so in their own implementation, the default implementation expects you to do something like:

```ts
import {DefaultLocaleHandler} from "./localization/default-locale-handler";
import {Locale as DefaultLocale} from "./locales/en-us"

let localeHandler = new DefaultLocaleHandler();
localeHandler.useLocale("en-us", DefaultLocale);
```

So it will just expect a JS object containing the required messages, however there is a prototype handler which would dynamically load based off a path (using the dynamic `import` approach) but this is more there for people who want to make their own `ILocaleHandler` implementation to see how that works.

Anyway this is a first stab at what seems like a sensible approach to the problem, and I appreciate you have probably moved on now, but will update the ticket as and when its done, I just need to update the other treacherous libs to support this new core version.

**Comment by grofit** [comment]
This has been added as part of 0.17 release, so closing this. Feel free to raise more issues related to this if you want to discuss the specific implementation or expanding this.
