### ISSUE TITLE
Creating a ValidationGroup against an undefined object throws errors

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#5]
If the user does not have a model assigned at the time of setting rules, an exception is thrown.
A workaround is to define `var user = {}`, but it would be convenient if the validation was skipped (and marked as invalid?) if a model was not present.
This is particularly applicable in Typescript, where initial values must either be set to a new instance of the object or cast to the appropriate type:
`private user:UserDTO = new UserDTO();` or `private user:UserDTO = <UserDTO>{};`
Not difficult, but unintuitive and a bit messy.

**Comment by grofit** [comment]
On this subject I don't see an exception being bad, granted I could make it a custom exception but if you were to assign an object which was not instantiated, when the object was instantiated you would not be pointing to the right model in the validator anyway so this would force you to do something like:

```
var model;
var validationGroup = createGroup(model, someRuleset); // Assuming no exception

model = new SomeModel();
validationGroup.changeModelTarget(model);
```

So I am not sure what the correct behaviour would be if you pass in an empty model, its fine passing in a model which is instantiated but empty, but to pass in something which is undefined or null imo should raise an exception.

However I am happy to discuss this further.

**Comment by grofit** [comment]
Just to keep this ticket up to date I currently have a branch where this use case is supported, however I also wanted to try and support the use case of someone with an empty object which is then populated as well as undefined objects, so this is still ongoing. However I am listing it as an enhancement not a bug, as it was not an intended use case.

**Comment by grofit** [comment]
Basic support for this has been added in version 0.7.0, if there are use cases not captured off the back of this feel free to re-open.
