### ISSUE TITLE
changeValidationTarget causes error checking previousValue

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#6]
When changeValidationTarget is used to change an object and the old one is released, an error is thrown when references to previousValue are made internally.
e.g. https://github.com/grofit/treacherous/blob/9ae2629075bdb36978900c353c7e0859550e16e8/dist/treacherous.js#L1231

**Comment by grofit** [comment]
Will look into it, it may be simpler to just add a new model watcher and remove the old one if this is the case.

**Comment by grofit** [comment]
I *think* this may be fixed as part of 0.7.0 as this tightens up support for undefined/null properties, if this issue does still persist then feel free to re-raise and if we can get a test case for it to add to the list it would be great.
