### ISSUE TITLE
Custom messages for validation rules

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#7]
The addRule would benefit from an optional parameter accepting either a string or a function to resolve the error message displayed if validation fails, or perhaps another fluent function.
This is particularly important for regex rules, and the functionality could double as part of the i18n.
How about
`.forProperty("uRLAlias").addRule("regex", url).message("Enter a web address, you plonker")`
or
`.forProperty("uRLAlias").addRule("regex", url).message(resolveMsg)`
?
Passing any function or a string the current value and/or rule options object might be helpful too.

**Comment by grofit** [comment]
Will look into this and discuss further, as currently there is outstanding work to be done on supporting multiple languages, at a high level it should just be a case of splitting the strings out into another class and referencing them from the rule code, but this would effect this feature.
